[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"]}
axum = {version = "0.8.9", features = ["ws"]}
uuid = "1.26.0"
serde_json = { version = "1.0.151"}
serde = { version = "1.0.229", features = ["derive"] }
surrealdb = "3.2.4"
dotenvy = "0.15.7"
tower-http = { version = "0.7.1", features = ["cors"] }
